---
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/db_scheme
  value: &external_cc_database_scheme "((external_database_type))"
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/port
  value: &external_cc_database_port "((external_database_port))"
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/databases/tag=cc/name
  value: &external_cc_database_name "((external_cc_database_name))"
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: &external_cc_database_address "((external_cc_database_address))"
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/roles/name=cloud_controller/password
  value: &external_cc_database_password "((external_cc_database_password))"
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/roles/name=cloud_controller/name
  value: &external_cc_database_username "((external_cc_database_username))"
  